name: Setup changeset pre-release
description: Check if there are changesets in the rep

inputs: 
  is_pre_release:
    description: 'Is this a pre-release'
    required: true
    type: boolean

runs:
  using: 'composite'
  steps:
      - name: log
        shell: bash
        run: |
          pwd
          ls
      - name: Get current release mode
        id: current_release_mode
        shell: bash
        uses: ./.github/actions/is-pre-release #  Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/home/runner/work/test-changesets-automerge/test-changesets-automerge/.github/actions/setup-changeset-pre-release'. Did you forget to run actions/checkout before running your local action?

      - name: Prepare changeset pre-release
        if: ${{ inputs.is_pre_release }} == 'true' && steps.current_release_mode.outputs.in_pre_release_mode == 'false'
        shell: bash
        run: |
          pnpm run version:pre-release
          git add .
          git commit -m "chore: prepare pre-release"

      - name: Prepare changeset release
        if: ${{ inputs.is_pre_release }} == 'false' && steps.current_release_mode.outputs.in_pre_release_mode == 'true'
        shell: bash
        run: |
          pnpm run version:pre-release:exit
          git add .
          git commit -m "chore: exit pre-release"