name: Setup changeset pre-release
description: Check if there are changesets in the rep

inputs: 
  is_pre_release:
    description: 'Is this a pre-release'
    required: true
    type: boolean

runs:
  using: 'composite'
  steps:
      - name: Prepare changeset pre-release
        if: ${{ inputs.is_pre_release == 'true' }}
        shell: bash
        run: pnpm run version:pre-release

      - name: Prepare changeset release
        if: ${{ inputs.is_pre_release == 'false' }}
        shell: bash
        run: pnpm run version:pre-release:exit