name: Git user info
description: Setup git user info

runs:
  using: 'composite'
  steps:

  - name: Setup git user info
    shell: bash
    run: | 
      git config user.name "github-actions[bot]"
      git config user.email "41898282+github-actions[bot]@users.noreply.github.com"   