name: Is Pre-release
description: Check if release is in pre-release mode

outputs:
  in_pre_release_mode:
    description: 'If the release is in pre-release mode'
    value: ${{ steps.changesets.outputs.in_pre_release_mode }}

runs:
  using: 'composite'
  steps:

  - name: Check if release is in pre-release mode
    id: changesets
    shell: bash
    run: |
            if [[ -f .changeset/pre.json ]]; then
              if [[ "$(jq -r '.mode' .changeset/pre.json)" == "pre" ]]; then
                echo "Pre-release mode is enabled."
                echo "in_pre_release_mode=true" >> $GITHUB_OUTPUT
              else
                echo "Pre-release mode is disabled."
                echo "in_pre_release_mode=false" >> $GITHUB_OUTPUT
              fi
            else
              echo "Normal release mode (not in pre-release mode)."
              echo "in_pre_release_mode=false" >> $GITHUB_OUTPUT
            fi
