name: Release main

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release production
    permissions:
      contents: write
      packages: write
    uses: ./.github/workflows/release.yml
    with:
      pre_release: false
