name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

env: 
  node_version: 22

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      packages: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - run: git config user.name "github-actions[bot]"
      - run: git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Setup Node.js ${{env.node_version}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{env.node_version}}
          registry-url: 'https://npm.pkg.github.com'

      - uses: pnpm/action-setup@v4
      
      - name: Install Dependencies
        run: pnpm i

      - name: Check for changesets
        id: changesets
        run: |
          if pnpm run version:hasChanges; then
            echo "new changesets found."
            echo "hasChanges=true" >> $GITHUB_OUTPUT
          else
            echo "No changesets has been found."
            echo "hasChanges=false" >> $GITHUB_OUTPUT
          fi

      - name: Build
        if: steps.changesets.outputs.hasChanges == 'true'
        run: pnpm build

      - name: Update Version
        if: steps.changesets.outputs.hasChanges == 'true'
        run: pnpm version:bump
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to GitHub Packages
        if: steps.changesets.outputs.hasChanges == 'true'
        run: pnpm ci:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create git Tag
        if: steps.changesets.outputs.hasChanges == 'true'
        run: pnpm run ci:git:tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Create Release Pull Request or Publish to npm
      #   id: changesets
      #   uses: changesets/action@v1
      #   with:
      #     publish: pnpm ci:publish
      #     commit: "chore(release): changesets versioning & publication"
      #     title: "Changesets: Versioning & Publication"
      #     createGithubReleases: true
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Enable auto-merge for Changesets PRs
      #   if: steps.changesets.outputs.hasChangesets
      #   run: gh pr --repo "$REPO" merge --auto --merge "$PR_NUM"
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     PR_NUM: ${{ steps.changesets.outputs.pullRequestNumber }}
      #     REPO: ${{ github.repository }}
